services:
  - type: web
    name: unified-checkout-test
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://card-payment-hso8.onrender.com

